package.json, src/components/App.js, src/components/App.test.js, src/components/home/Home.js, src/components/home/Home.test.js, src/index.js, yarn.lock
Configura rotas principais e navegação pelos principais componentes
=> Rotas e navegação principal

.travis.yml, package.json, yarn.lock
Setup Codeclimate to verify code coverage
=> Setup codeclimate

README.md
=> Atualiza o Readme para conter o link para o wiki.

.travis.yml
.travis.yml para ativar as notificações no Gitter. [https://gitter.im/Coletivo-Enegrecer/Enegrecer](url)
connect #34
=> Adicionando webhook

.editorconfig
**CHANGELOG**
- Adiciona .editorconfig para evitar conflito entre multiplos editores.
**ISSUE:** #62
=> Adiciona .editorconfig para evitar conflito entre multiplos editores.

.travis.yml, package.json, src/utils/validacoesCamposForm.js, src/utils/validacoesCamposForm.test.js
Este pull request é para tratar a questão da Issue 97.
Além dela foram feitas as seguintes alterações para que o build passasse:
1) As bibliotecas React e React estavam em dev package.json.
2) Foi comentando um método temAcentuacao que estava quebrando o yarn build.
=> Acerto Travis - Para não acessar o report de cobertura

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.md, LICENSE, README.md
N/A
Serão adicionados os arquivos de documentação para guiar as pessoas que quiserem colaborar no projeto **Verdade Seja Dita**
A [documentação oficial do git](https://help.github.com/articles/helping-people-contribute-to-your-project/) e o repositório do ATOM foram os recursos usados como guia para criação do processo e dos artefatos.
Facilitar a contribuição Open source
Necessita de revisão periódica
N/A
N/A
=> Melhorar documentação - Código de conduta e guia de contribuição.

.hawkeyerc, .travis.yml, ci/security-checks.sh
Adiciona um step na pipeline de check de segurança automático.
Adicionado script de teste de segurança em `ci` e arquivo oculto na raiz com a configuração básica para o teste de segurança. Ele somente falha caso algo crítico seja detectado.
Faz o dependency check e verificação de possíveis falhas de segurança mais comuns.
Pode aumentar o ciclo de feedback até o deploy.
=> :lock: Adiciona passo de teste de segurança na pipeline

src/actions/criarDenunciaActions.js, src/containers/denuncias/NovaDenunciaContainer.js, src/sagas/denuncias.js, src/sagas/denuncias.test.js
Melhorias de código no projeto
Organizar a estrutura de pasta para as actions e remoção de action nao utilizadas
Maior organização de pastas e arquivos do projeto
N/A
N/A
N/A
=> Organizar a estrutura de pasta para as actions

README.md
Documentação do projeto.
O link para documentação de como contribuir para o projeto estava quebrado.Agora foi corrigido.
Acesso direto a documentação de como contribuir para o projeto.
N/A
N/A
N/A
=> Acerto no link de contribuição que estava quebrado

src/containers/denuncias/NovaDenunciaContainer.test.js, src/containers/denuncias/validaDenuncia.js, src/containers/denuncias/validaDenuncia.test.js
Novo Regex para a validação de telefone para o seguinte formato: (xx) xxxxx-xxxx, sendo o quinto dígito opicional pensando em números residencias.
=> [Luciana/Thiago] Adicionar validação de telefone pra vítima

README.md, package.json, src/Tela.js, src/assets/styles/index.scss, src/components/FormGroups.js, src/components/denuncias/DetalhamentoDenuncia.js, src/components/denuncias/testemunha/NovaTestemunhaForm.js, src/components/denuncias/vitima/NovaVitimaForm.js, src/containers/denuncias/NovaDenunciaContainer.js, src/index.js
Remocão  do Boostrap 
1)  Remoção do Bootstrap . 
2) Adoção CSS Grid. 
Adoção de uma única biblioteca de layout para todo projeto.
Possíveis de quebra de componentes.
N/A
N/A
=> Remoção do bootstrap

.eslintrc.json, package.json, src/components/comum/checkbox/index.js, src/components/comum/combobox/index.js, src/components/comum/nome/index.js, src/components/denuncias/DetalhamentoDenuncia.js, src/components/denuncias/DetalhamentoDenuncia.test.js, src/components/denuncias/NovaDenunciaForm.js, src/components/denuncias/NovaDenunciaForm.test.js, src/components/denuncias/testemunha/NovaTestemunhaForm.js, src/components/denuncias/testemunha/NovaTestemunhaForm.test.js, src/components/denuncias/vitima/NovaVitimaForm.js, src/components/denuncias/vitima/NovaVitimaForm.test.js, src/components/home/Home.js, src/components/home/Nav.js, src/components/proximosPassos/ProximosPassos.test.js, src/containers/denuncias/NovaDenunciaContainer.js, src/containers/denuncias/NovaDenunciaContainer.test.js, src/containers/denuncias/validaDenuncia.js, src/containers/denuncias/validaDenuncia.test.js, src/index.js, src/reducers/denunciaComSucessoReducer.js, src/routes/Painel.js, src/store/index.js, src/utils/helpers.js, src/utils/helpers.test.js, src/utils/materializeCSS.js
Tornar as validações do Eslint mais abrangentes levando a maior padronização de código.
Adição das seguintes validações: 
1) Validação de sempre ponto vírgula nos final das instruções
2) Número de linhas em branco entre imports, classes e funçoes.
Maior padronização de código
N/A
N/A
=> Adição de validações do Eslint

package.json
…eployada no firebase
A aplicação mostra uma página em branco quando está no firebase.
N/A
N/A
N/A
=> Aplicação estava exibindo uma página no firebase

src/components/sobre/Sobre.js, src/components/sobre/Sobre.test.js, src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js, src/components/sobre/componentes/Colaborador.js, src/components/sobre/componentes/Colaborador.test.js, src/components/sobre/componentes/__snapshots__/Colaborador.test.js.snap, src/components/sobre/css/sobre.css, src/routes/Routes.js, src/routes/Routes.test.js, src/routes/__snapshots__/Routes.test.js.snap
- Visualizar as informações da pagina sobre.
=> [31 ver as informações do verdade seja dita]

public/index.html, src/components/comum/campoTexto/index.js, src/components/denuncias/FormSection.js, src/components/denuncias/NovaDenunciaForm.js, src/components/denuncias/agressor/AgressorForm.js, src/components/denuncias/agressor/__snapshots__/AgressorForm.test.js.snap, src/components/denuncias/denuncia.css, src/components/denuncias/denunciante/DenuncianteForm.js, src/components/denuncias/denunciante/__snapshots__/DenuncianteForm.test.js.snap, src/components/denuncias/descricao/FormDescricao.js, src/components/denuncias/descricao/__snapshots__/FormDescricao.test.js.snap, src/components/denuncias/informacoesLegais/FormInformacoesLegais.js, src/components/denuncias/informacoesLegais/__snapshots__/FormInformacoesLegais.test.js.snap, src/components/denuncias/vitima/NovaVitimaForm.js, src/components/denuncias/vitima/__snapshots__/NovaVitimaForm.test.js.snap, src/containers/denuncias/NovaDenunciaContainer.js
Componentizei as seções do formulário de denúncia pra que os estilos possam ser reutilizados, uma vez que o padrão de seções se repete ao longo do formulário.
Além disso, realizei algumas alterações relacionadas ao css da página.
Reaproveitamento do estilo das seções do formulário e código mais enxuto.
NA
Devemos verificar qual vai ser a forma de interação com o formulário, pois isso poderá afetar na estrutura do css.
NA
NA
=> Ajustes formulario denuncia

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
Não se aplica.
Adiciona o nome, papel e foto das pessoas colaboradoras no arquivo *colaboradores.js*.
Não se aplica.
Não se aplica.
Não se aplica.
Não se aplica.
=> Adiciona nome, papel e foto das pessoas colaboradoras na página sobre

src/components/home/Home.js, src/components/home/Home.test.js, src/components/home/__snapshots__/Home.test.js.snap
=> Insere imagem na home

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
=> Revert das fotos das pessoas colaboradoras na pagina sobre

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
Não se aplica.
Adiciona as pessoas colaboradoras de Recife no arquivo *colaboradores.js*.
Não se aplica.
Não se aplica.
Não se aplica.
Não se aplica.
=> Adiciona pessoas colaboradoras de Recife

src/components/home/Home.js, src/routes/Routes.js, src/routes/__snapshots__/Routes.test.js.snap
NA
Acredito que os componentes de Menu e Rodapé não precisam estar envoltos do Route, uma vez que eles se repetem em cada uma das telas.
NA
NA
NA
NA
=> Remove Route dos componentes de header e rodapé.

src/components/home/css/home.css
N/A
Altera cor de barra lateral na homepage para preto
Melhor harmonia com as cores do portal
N/A
N/A
N/A
=> Altera cor de barra lateral na homepage

firebase.json, src/components/home/css/home.css
N/A
Sincroniza development com master
N/A
N/A
N/A
N/A
=> Sincroniza development com master

src/components/estatistica/Estatistica.js, src/components/estatistica/css/estatistica.css, src/components/home/Home.js, src/components/home/__snapshots__/Home.test.js.snap, src/components/home/css/home.css, src/components/menu/Menu.js
=> Adiciona o css da estatística

firebase.json
=> Retorna as configurações iniciais do firebase

src/components/menu/Menu.js, src/components/menu/__snapshots__/Menu.test.js.snap, src/components/menu/menu.css, src/components/rodape/Rodape.js
N/a
Adiciona a propriedade 'col 12' a primeira div do menu e do rodapé; adiciona padding de 5px aos links do menu.
Melhor visualização do Menu e Rodapé nos diferentes tamanhos de telas dos dispositivos móveis.
N/a
Close ISSUE-172
N/a
=> [ISSUE-172] Adiciona responsividade ao menu e rodapé

src/components/estatistica/Estatistica.js, src/components/estatistica/css/estatistica.css, src/components/home/css/home.css
Deixa a home mais responsiva
Responsividade
=> Deixa a home mais responsiva

src/components/comum/checkbox/__snapshots__/CheckBox.test.js.snap, src/components/comum/checkbox/index.js, src/components/comum/comboboxEstado/index.js, src/components/comum/nome/__snapshots__/Nome.test.js.snap, src/components/comum/nome/index.js, src/components/comum/validacoes/index.js, src/components/denuncias/NovaDenunciaForm.js, src/components/denuncias/__snapshots__/DetalhamentoDenuncia.test.js.snap, src/components/denuncias/agressor/AgressorForm.js, src/components/denuncias/agressor/__snapshots__/AgressorForm.test.js.snap, src/components/denuncias/denuncia.css, src/components/denuncias/denunciante/DenuncianteForm.js, src/components/denuncias/denunciante/__snapshots__/DenuncianteForm.test.js.snap, src/components/denuncias/descricao/__snapshots__/FormDescricao.test.js.snap, src/components/denuncias/vitima/NovaVitimaForm.js, src/components/denuncias/vitima/__snapshots__/NovaVitimaForm.test.js.snap, src/components/home/Home.js, src/containers/denuncias/NovaDenunciaContainer.js
Inlcui validações em campos obrigatórios no formulário de denúncia.
A partir de agora qualquer tentativa de submissão sem preencher os campos obrigatórios do form será barrada pelo redux-form.
Informações obrigatórias deverão ser preenchidas.
NA
NA
NA
NA
=> Validações form

public/index.html, src/components/menu/Menu.js, src/components/menu/__snapshots__/Menu.test.js.snap, src/components/menu/menu.css
N/a
Adiciona menu adequado para dispositvos com menor tamanho de tela.
Melhor visualização do menu em telas menores
N/a
Issue-172
Uso do materializeCss para renderizar o menu
=> [ISSUE-172] Adiciona menu responsivo ao redimensionamento de tela

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
N/a
Adiociona Helena Silva como colaboradora na página; adiciona a foto no DB;
N/a
N/a
ISSUE-213
N/a
=> Adiciona Helena Silva como colaboradora na página sobre

src/components/sobre/Sobre.js, src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/componentes/Colaborador.js, src/components/sobre/componentes/__snapshots__/Colaborador.test.js.snap, src/components/sobre/css/sobre.css
N/a
Adiciona classes do MaterializeCss na pagina sobre para torna-la responsiva.
Melhor renderização da página em diferentes tamanhos de telas.
N/a
Close #215 
N/a
=> [ISSUE-215] Torna a página Sobre responsiva

src/components/coletivoEnegrecer/ColetivoEnegrecer.js, src/components/coletivoEnegrecer/__snapshots__/ColetivoEnegrecer.test.js.snap, src/components/coletivoEnegrecer/coletivo-enegrecer.css
N/a
Refatora a pagina do Coletivo Enegrecer para torná-la responsiva.
Melhora a renderização da página em diferentes tamanhos de tela.
N/a
Close #170 
N/a
=> [ISSUE-170] Adiciona responsividade na página O Coletivo Enegrecer

src/components/estatistica/css/estatistica.css, src/components/home/Home.js, src/components/home/__snapshots__/Home.test.js.snap, src/components/home/css/home.css, src/components/menu/Menu.js, src/components/menu/menu.css, src/components/sobre/Sobre.js, src/components/sobre/__snapshots__/Sobre.test.js.snap
=> Ajusta o CSS do Menu

src/components/menu/Menu.js
N/A
Adiciona função esconde menu para que feche apos a mudança de URL quando está na exibição mobile.
N/A
N/A
N/A
N/A
=> Adiciona função JS para fechar o menu em mobile

src/routes/Routes.js, src/routes/__snapshots__/Routes.test.js.snap
N/A
* As rotas do moderador estavam sendo tratadas como erro 404.
* As rotas de fluxo devem ser colocadas antes da  rota de tratamento do erro 404 no arquivo Routes.js. Quando colocadas depois não são tratadas como rotas válidas.
* As rotas são direciondas corretamente.
* Pode ocorrer novamente se colocarmos outras rotas abaixo do tratamento de erro 404.
N/A
N/A
=> [BUG-ROTAS] Corrige bug de pagina não encontrada e rotas privadas

src/components/comum/combobox/__snapshots__/Combobox.test.js.snap, src/components/comum/combobox/index.js, src/components/moderador/DenunciaRow.js, src/components/moderador/menu-moderador.css, src/components/moderador/menuModerador.js, src/components/moderador/painel-moderador.css, src/components/moderador/painelModerador.js, src/imagens/botao-expandir.svg, src/imagens/botao-remover-denuncia.svg, src/imagens/botao-retrair.svg
N/A
[Atividade em andamento]
Pairing w/ @danielcn & @paulogama 
Criamos a tabela que mostra as denúncias cadastradas na base de dados
Ajustamos o design do header do painel do moderador
Pairing w/ @PatrickRoberto 
Realizamos ajustes de layout e inclusão de botões no painel do moderador 
É possível fazer o logout do painel do moderador e visualizar os detalhes das denúncias cadastradas na base de dados.
NA
NA
NA
=> Issue 165 - Classificar Denúncia

src/components/denuncias/SecaoForm.js, src/components/denuncias/denuncia.css, src/containers/denuncias/NovaDenunciaContainer.js
N/A
Adiciona ancora nos itens do menu lateral do Formulario de denuncia.
Closes #243 
N/A
=> ISSUE-243 Adiciona ancora nos itens do menu lateral do Formulario de denuncia

README.md
Não aplicável
Foi adicionada a seção **Configurando seu ambiente** no arquivo README principal do projeto. 
Nessa seção estão as informações das instalações que o colaborador deve realizar/verificar antes de começar a colaborar para o projeto.
Novos colaboradores poderam verificar os pré requisitos para executar e/ou desenvolver o projeto, desta forma, evetando erros que podem ocorrem por falta de alguma dependência do projeto.
Não aplicável
ISSUE-276
Não aplicável
=> Adicionando no README os pré requisitos para executar e desenvolver o projeto

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
Não se aplica.
Não se aplica.
Não se aplica.
Não se aplica.
Não se aplica.
Não se aplica.
=> Adicionar Fernando Machado aos colaboradores

src/components/sobre/__snapshots__/Sobre.test.js.snap, src/components/sobre/colaboradores.js
Não aplicável
Adicionar Tatiane Nogueira às colaboradoras
Não aplicável
Não aplicável
Não aplicável
Não aplicável
=> Adicionar Tatiane Nogueira às colaboradoras

README.md
=> Add on readme file NVM link

src/components/estatistica/css/estatistica.css, src/components/estatistica/css/estatisticaMobile.css
Ajustes da porcentagem e do alinhamento do texto abaixo.
=> Resolução da Issue #300, porcentagem estourando o box.

src/components/denuncias/NovaDenunciaForm.js, src/components/denuncias/denuncia.css, src/components/estatistica/css/estatisticaMobile.css, src/components/home/css/home.css, src/components/navbar/Navbar.js, src/components/navbar/__snapshots__/Navbar.test.js.snap, src/containers/denuncias/NovaDenunciaContainer.js
N/A
Ajusta o design da página para diferentes tamanhos de tela
N/A
N/A
N/A
N/A
=> Ajusta design mobile

src/components/navbar/Navbar.js, src/components/navbar/__snapshots__/Navbar.test.js.snap, src/components/navbar/navbar.css, src/components/sobreColetivo/coletivo-enegrecer.css
=> Ajusta design desktop
